/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_examplejni_lib_native_cargarLibNative */

#ifndef _Included_com_examplejni_lib_native_cargarLibNative
#define _Included_com_examplejni_lib_native_cargarLibNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_examplejni_lib_native_cargarLibNative
 * Method:    datosLibro
 * Signature: (Lcom/examplejni/biblioteca/Libro;)V
 */
JNIEXPORT void JNICALL Java_com_examplejni_lib_1native_cargarLibNative_datosLibro
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
